[package]
name = "sui"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "A injection tool for executable formats (ELF, PE, Mach-O) that allows you to embed files into existing binary and extract them at runtime"
homepage = "https://sui.littledivy.com"
repository = "https://github.com/littledivy/sui"

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"

